// Lumina Protocol Buffer Definitions
// Version: v1
// Purpose: Define message types for AI Agent communication with Lumina TUI framework

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/lumina.proto

package lumiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ComponentInstance represents a running component instance.
type ComponentInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Props         map[string]*Value      `protobuf:"bytes,4,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	State         map[string]*Value      `protobuf:"bytes,5,rep,name=state,proto3" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Dirty         bool                   `protobuf:"varint,6,opt,name=dirty,proto3" json:"dirty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentInstance) Reset() {
	*x = ComponentInstance{}
	mi := &file_proto_v1_lumina_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentInstance) ProtoMessage() {}

func (x *ComponentInstance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentInstance.ProtoReflect.Descriptor instead.
func (*ComponentInstance) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{0}
}

func (x *ComponentInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComponentInstance) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ComponentInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentInstance) GetProps() map[string]*Value {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *ComponentInstance) GetState() map[string]*Value {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ComponentInstance) GetDirty() bool {
	if x != nil {
		return x.Dirty
	}
	return false
}

// ComponentFactory defines a component template.
type ComponentFactory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	IsComponent   bool                   `protobuf:"varint,3,opt,name=is_component,json=isComponent,proto3" json:"is_component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentFactory) Reset() {
	*x = ComponentFactory{}
	mi := &file_proto_v1_lumina_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentFactory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentFactory) ProtoMessage() {}

func (x *ComponentFactory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentFactory.ProtoReflect.Descriptor instead.
func (*ComponentFactory) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{1}
}

func (x *ComponentFactory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentFactory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComponentFactory) GetIsComponent() bool {
	if x != nil {
		return x.IsComponent
	}
	return false
}

// VNode represents a virtual DOM node.
type VNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // "box", "text", "button", etc.
	Props         map[string]*Value      `protobuf:"bytes,2,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Children      []*VNode               `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VNode) Reset() {
	*x = VNode{}
	mi := &file_proto_v1_lumina_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VNode) ProtoMessage() {}

func (x *VNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VNode.ProtoReflect.Descriptor instead.
func (*VNode) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{2}
}

func (x *VNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *VNode) GetProps() map[string]*Value {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *VNode) GetChildren() []*VNode {
	if x != nil {
		return x.Children
	}
	return nil
}

// RenderResult contains the output of a component render.
type RenderResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Vdom          *VNode                 `protobuf:"bytes,2,opt,name=vdom,proto3" json:"vdom,omitempty"`
	RenderTimeUs  int64                  `protobuf:"varint,3,opt,name=render_time_us,json=renderTimeUs,proto3" json:"render_time_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResult) Reset() {
	*x = RenderResult{}
	mi := &file_proto_v1_lumina_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResult) ProtoMessage() {}

func (x *RenderResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResult.ProtoReflect.Descriptor instead.
func (*RenderResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{3}
}

func (x *RenderResult) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *RenderResult) GetVdom() *VNode {
	if x != nil {
		return x.Vdom
	}
	return nil
}

func (x *RenderResult) GetRenderTimeUs() int64 {
	if x != nil {
		return x.RenderTimeUs
	}
	return 0
}

// HookCall represents a single hook invocation.
type HookCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HookName      string                 `protobuf:"bytes,1,opt,name=hook_name,json=hookName,proto3" json:"hook_name,omitempty"` // "useState", "useEffect", etc.
	Args          []*Value               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Result        *Value                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookCall) Reset() {
	*x = HookCall{}
	mi := &file_proto_v1_lumina_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookCall) ProtoMessage() {}

func (x *HookCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookCall.ProtoReflect.Descriptor instead.
func (*HookCall) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{4}
}

func (x *HookCall) GetHookName() string {
	if x != nil {
		return x.HookName
	}
	return ""
}

func (x *HookCall) GetArgs() []*Value {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *HookCall) GetResult() *Value {
	if x != nil {
		return x.Result
	}
	return nil
}

// StateUpdate represents a state change.
type StateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	OldValue      *Value                 `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue      *Value                 `protobuf:"bytes,4,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_proto_v1_lumina_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{5}
}

func (x *StateUpdate) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *StateUpdate) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StateUpdate) GetOldValue() *Value {
	if x != nil {
		return x.OldValue
	}
	return nil
}

func (x *StateUpdate) GetNewValue() *Value {
	if x != nil {
		return x.NewValue
	}
	return nil
}

// MouseEvent represents a mouse interaction.
type MouseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "click", "move", "wheel"
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Button        string                 `protobuf:"bytes,4,opt,name=button,proto3" json:"button,omitempty"` // "left", "right", "middle"
	ClickCount    int32                  `protobuf:"varint,5,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseEvent) Reset() {
	*x = MouseEvent{}
	mi := &file_proto_v1_lumina_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseEvent) ProtoMessage() {}

func (x *MouseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseEvent.ProtoReflect.Descriptor instead.
func (*MouseEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{6}
}

func (x *MouseEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MouseEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MouseEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MouseEvent) GetButton() string {
	if x != nil {
		return x.Button
	}
	return ""
}

func (x *MouseEvent) GetClickCount() int32 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

// KeyboardEvent represents a keyboard interaction.
type KeyboardEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "keydown", "keyup", "keypress"
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Ctrl          bool                   `protobuf:"varint,4,opt,name=ctrl,proto3" json:"ctrl,omitempty"`
	Shift         bool                   `protobuf:"varint,5,opt,name=shift,proto3" json:"shift,omitempty"`
	Alt           bool                   `protobuf:"varint,6,opt,name=alt,proto3" json:"alt,omitempty"`
	Meta          bool                   `protobuf:"varint,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardEvent) Reset() {
	*x = KeyboardEvent{}
	mi := &file_proto_v1_lumina_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardEvent) ProtoMessage() {}

func (x *KeyboardEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardEvent.ProtoReflect.Descriptor instead.
func (*KeyboardEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{7}
}

func (x *KeyboardEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *KeyboardEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyboardEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *KeyboardEvent) GetCtrl() bool {
	if x != nil {
		return x.Ctrl
	}
	return false
}

func (x *KeyboardEvent) GetShift() bool {
	if x != nil {
		return x.Shift
	}
	return false
}

func (x *KeyboardEvent) GetAlt() bool {
	if x != nil {
		return x.Alt
	}
	return false
}

func (x *KeyboardEvent) GetMeta() bool {
	if x != nil {
		return x.Meta
	}
	return false
}

// EventMessage wraps all event types.
type EventMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ComponentId string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	EventType   string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*EventMessage_Mouse
	//	*EventMessage_Keyboard
	Event         isEventMessage_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_proto_v1_lumina_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{8}
}

func (x *EventMessage) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *EventMessage) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventMessage) GetEvent() isEventMessage_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventMessage) GetMouse() *MouseEvent {
	if x != nil {
		if x, ok := x.Event.(*EventMessage_Mouse); ok {
			return x.Mouse
		}
	}
	return nil
}

func (x *EventMessage) GetKeyboard() *KeyboardEvent {
	if x != nil {
		if x, ok := x.Event.(*EventMessage_Keyboard); ok {
			return x.Keyboard
		}
	}
	return nil
}

type isEventMessage_Event interface {
	isEventMessage_Event()
}

type EventMessage_Mouse struct {
	Mouse *MouseEvent `protobuf:"bytes,3,opt,name=mouse,proto3,oneof"`
}

type EventMessage_Keyboard struct {
	Keyboard *KeyboardEvent `protobuf:"bytes,4,opt,name=keyboard,proto3,oneof"`
}

func (*EventMessage_Mouse) isEventMessage_Event() {}

func (*EventMessage_Keyboard) isEventMessage_Event() {}

// CreateComponent creates a new component instance.
type CreateComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ComponentType string                 `protobuf:"bytes,2,opt,name=component_type,json=componentType,proto3" json:"component_type,omitempty"`
	Props         map[string]*Value      `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateComponentRequest) Reset() {
	*x = CreateComponentRequest{}
	mi := &file_proto_v1_lumina_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateComponentRequest) ProtoMessage() {}

func (x *CreateComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateComponentRequest.ProtoReflect.Descriptor instead.
func (*CreateComponentRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{9}
}

func (x *CreateComponentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateComponentRequest) GetComponentType() string {
	if x != nil {
		return x.ComponentType
	}
	return ""
}

func (x *CreateComponentRequest) GetProps() map[string]*Value {
	if x != nil {
		return x.Props
	}
	return nil
}

type CreateComponentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Instance      *ComponentInstance     `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateComponentResponse) Reset() {
	*x = CreateComponentResponse{}
	mi := &file_proto_v1_lumina_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateComponentResponse) ProtoMessage() {}

func (x *CreateComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateComponentResponse.ProtoReflect.Descriptor instead.
func (*CreateComponentResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{10}
}

func (x *CreateComponentResponse) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *CreateComponentResponse) GetInstance() *ComponentInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

// UpdateComponent updates a component's props or state.
type UpdateComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Props         map[string]*Value      `protobuf:"bytes,2,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	State         map[string]*Value      `protobuf:"bytes,3,rep,name=state,proto3" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateComponentRequest) Reset() {
	*x = UpdateComponentRequest{}
	mi := &file_proto_v1_lumina_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateComponentRequest) ProtoMessage() {}

func (x *UpdateComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateComponentRequest.ProtoReflect.Descriptor instead.
func (*UpdateComponentRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateComponentRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *UpdateComponentRequest) GetProps() map[string]*Value {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *UpdateComponentRequest) GetState() map[string]*Value {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdateComponentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Instance      *ComponentInstance     `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateComponentResponse) Reset() {
	*x = UpdateComponentResponse{}
	mi := &file_proto_v1_lumina_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateComponentResponse) ProtoMessage() {}

func (x *UpdateComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateComponentResponse.ProtoReflect.Descriptor instead.
func (*UpdateComponentResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateComponentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateComponentResponse) GetInstance() *ComponentInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

// DeleteComponent removes a component instance.
type DeleteComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteComponentRequest) Reset() {
	*x = DeleteComponentRequest{}
	mi := &file_proto_v1_lumina_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteComponentRequest) ProtoMessage() {}

func (x *DeleteComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteComponentRequest.ProtoReflect.Descriptor instead.
func (*DeleteComponentRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteComponentRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

type DeleteComponentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteComponentResponse) Reset() {
	*x = DeleteComponentResponse{}
	mi := &file_proto_v1_lumina_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteComponentResponse) ProtoMessage() {}

func (x *DeleteComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteComponentResponse.ProtoReflect.Descriptor instead.
func (*DeleteComponentResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteComponentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// QueryComponent queries component information.
type QueryComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Fields        []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryComponentRequest) Reset() {
	*x = QueryComponentRequest{}
	mi := &file_proto_v1_lumina_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryComponentRequest) ProtoMessage() {}

func (x *QueryComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryComponentRequest.ProtoReflect.Descriptor instead.
func (*QueryComponentRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{15}
}

func (x *QueryComponentRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *QueryComponentRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type QueryComponentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *ComponentInstance     `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryComponentResponse) Reset() {
	*x = QueryComponentResponse{}
	mi := &file_proto_v1_lumina_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryComponentResponse) ProtoMessage() {}

func (x *QueryComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryComponentResponse.ProtoReflect.Descriptor instead.
func (*QueryComponentResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{16}
}

func (x *QueryComponentResponse) GetInstance() *ComponentInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

// ComponentTree requests the full component tree.
type ComponentTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeState  bool                   `protobuf:"varint,1,opt,name=include_state,json=includeState,proto3" json:"include_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentTreeRequest) Reset() {
	*x = ComponentTreeRequest{}
	mi := &file_proto_v1_lumina_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentTreeRequest) ProtoMessage() {}

func (x *ComponentTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentTreeRequest.ProtoReflect.Descriptor instead.
func (*ComponentTreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{17}
}

func (x *ComponentTreeRequest) GetIncludeState() bool {
	if x != nil {
		return x.IncludeState
	}
	return false
}

type ComponentTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roots         []*ComponentInstance   `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentTreeResponse) Reset() {
	*x = ComponentTreeResponse{}
	mi := &file_proto_v1_lumina_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentTreeResponse) ProtoMessage() {}

func (x *ComponentTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentTreeResponse.ProtoReflect.Descriptor instead.
func (*ComponentTreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{18}
}

func (x *ComponentTreeResponse) GetRoots() []*ComponentInstance {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *ComponentTreeResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// InspectComponent requests detailed component inspection.
type InspectComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectComponentRequest) Reset() {
	*x = InspectComponentRequest{}
	mi := &file_proto_v1_lumina_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectComponentRequest) ProtoMessage() {}

func (x *InspectComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectComponentRequest.ProtoReflect.Descriptor instead.
func (*InspectComponentRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{19}
}

func (x *InspectComponentRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

type InspectComponentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *ComponentInstance     `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	HookCalls     []*HookCall            `protobuf:"bytes,2,rep,name=hook_calls,json=hookCalls,proto3" json:"hook_calls,omitempty"`
	CreatedAtUs   int64                  `protobuf:"varint,3,opt,name=created_at_us,json=createdAtUs,proto3" json:"created_at_us,omitempty"`
	LastRenderUs  int64                  `protobuf:"varint,4,opt,name=last_render_us,json=lastRenderUs,proto3" json:"last_render_us,omitempty"`
	RenderCount   int32                  `protobuf:"varint,5,opt,name=render_count,json=renderCount,proto3" json:"render_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectComponentResponse) Reset() {
	*x = InspectComponentResponse{}
	mi := &file_proto_v1_lumina_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectComponentResponse) ProtoMessage() {}

func (x *InspectComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectComponentResponse.ProtoReflect.Descriptor instead.
func (*InspectComponentResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{20}
}

func (x *InspectComponentResponse) GetInstance() *ComponentInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *InspectComponentResponse) GetHookCalls() []*HookCall {
	if x != nil {
		return x.HookCalls
	}
	return nil
}

func (x *InspectComponentResponse) GetCreatedAtUs() int64 {
	if x != nil {
		return x.CreatedAtUs
	}
	return 0
}

func (x *InspectComponentResponse) GetLastRenderUs() int64 {
	if x != nil {
		return x.LastRenderUs
	}
	return 0
}

func (x *InspectComponentResponse) GetRenderCount() int32 {
	if x != nil {
		return x.RenderCount
	}
	return 0
}

// Value represents a dynamic value that can be any JSON-compatible type.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_StringValue
	//	*Value_IntValue
	//	*Value_NumberValue
	//	*Value_BoolValue
	//	*Value_ListValue
	//	*Value_MapValue
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_v1_lumina_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{21}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Value.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetMapValue() *MapValue {
	if x != nil {
		if x, ok := x.Value.(*Value_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,3,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,5,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_MapValue struct {
	MapValue *MapValue `protobuf:"bytes,6,opt,name=map_value,json=mapValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Value() {}

func (*Value_IntValue) isValue_Value() {}

func (*Value_NumberValue) isValue_Value() {}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_ListValue) isValue_Value() {}

func (*Value_MapValue) isValue_Value() {}

// ListValue represents a list of values.
type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Value               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_proto_v1_lumina_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{22}
}

func (x *ListValue) GetItems() []*Value {
	if x != nil {
		return x.Items
	}
	return nil
}

// MapValue represents a map of string keys to values.
type MapValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]*Value      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	mi := &file_proto_v1_lumina_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValue.ProtoReflect.Descriptor instead.
func (*MapValue) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{23}
}

func (x *MapValue) GetEntries() map[string]*Value {
	if x != nil {
		return x.Entries
	}
	return nil
}

// BatchRequest contains multiple operations in one request.
type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*Operation           `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_proto_v1_lumina_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{24}
}

func (x *BatchRequest) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationType string                 `protobuf:"bytes,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"` // "create", "update", "delete", "query"
	ComponentId   string                 `protobuf:"bytes,2,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Params        map[string]*Value      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_proto_v1_lumina_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{25}
}

func (x *Operation) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *Operation) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *Operation) GetParams() map[string]*Value {
	if x != nil {
		return x.Params
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*OperationResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_proto_v1_lumina_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{26}
}

func (x *BatchResponse) GetResults() []*OperationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type OperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResult) Reset() {
	*x = OperationResult{}
	mi := &file_proto_v1_lumina_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResult) ProtoMessage() {}

func (x *OperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_lumina_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResult.ProtoReflect.Descriptor instead.
func (*OperationResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_lumina_proto_rawDescGZIP(), []int{27}
}

func (x *OperationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OperationResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_v1_lumina_proto protoreflect.FileDescriptor

const file_proto_v1_lumina_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/lumina.proto\x12\tlumina.v1\"\xf7\x02\n" +
	"\x11ComponentInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12=\n" +
	"\x05props\x18\x04 \x03(\v2'.lumina.v1.ComponentInstance.PropsEntryR\x05props\x12=\n" +
	"\x05state\x18\x05 \x03(\v2'.lumina.v1.ComponentInstance.StateEntryR\x05state\x12\x14\n" +
	"\x05dirty\x18\x06 \x01(\bR\x05dirty\x1aJ\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.lumina.v1.ValueR\x05value:\x028\x01\x1aJ\n" +
	"\n" +
	"StateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.lumina.v1.ValueR\x05value:\x028\x01\"Y\n" +
	"\x10ComponentFactory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12!\n" +
	"\fis_component\x18\x03 \x01(\bR\visComponent\"\xd1\x01\n" +
	"\x05VNode\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\x121\n" +
	"\x05props\x18\x02 \x03(\v2\x1b.lumina.v1.VNode.PropsEntryR\x05props\x12,\n" +
	"\bchildren\x18\x03 \x03(\v2\x10.lumina.v1.VNodeR\bchildren\x1aJ\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.lumina.v1.ValueR\x05value:\x028\x01\"}\n" +
	"\fRenderResult\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12$\n" +
	"\x04vdom\x18\x02 \x01(\v2\x10.lumina.v1.VNodeR\x04vdom\x12$\n" +
	"\x0erender_time_us\x18\x03 \x01(\x03R\frenderTimeUs\"w\n" +
	"\bHookCall\x12\x1b\n" +
	"\thook_name\x18\x01 \x01(\tR\bhookName\x12$\n" +
	"\x04args\x18\x02 \x03(\v2\x10.lumina.v1.ValueR\x04args\x12(\n" +
	"\x06result\x18\x03 \x01(\v2\x10.lumina.v1.ValueR\x06result\"\xa0\x01\n" +
	"\vStateUpdate\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12-\n" +
	"\told_value\x18\x03 \x01(\v2\x10.lumina.v1.ValueR\boldValue\x12-\n" +
	"\tnew_value\x18\x04 \x01(\v2\x10.lumina.v1.ValueR\bnewValue\"\x80\x01\n" +
	"\n" +
	"MouseEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x16\n" +
	"\x06button\x18\x04 \x01(\tR\x06button\x12\x1f\n" +
	"\vclick_count\x18\x05 \x01(\x05R\n" +
	"clickCount\"\xa4\x01\n" +
	"\rKeyboardEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04ctrl\x18\x04 \x01(\bR\x04ctrl\x12\x14\n" +
	"\x05shift\x18\x05 \x01(\bR\x05shift\x12\x10\n" +
	"\x03alt\x18\x06 \x01(\bR\x03alt\x12\x12\n" +
	"\x04meta\x18\a \x01(\bR\x04meta\"\xc0\x01\n" +
	"\fEventMessage\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12-\n" +
	"\x05mouse\x18\x03 \x01(\v2\x15.lumina.v1.MouseEventH\x00R\x05mouse\x126\n" +
	"\bkeyboard\x18\x04 \x01(\v2\x18.lumina.v1.KeyboardEventH\x00R\bkeyboardB\a\n" +
	"\x05event\"\xec\x01\n" +
	"\x16CreateComponentRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12%\n" +
	"\x0ecomponent_type\x18\x02 \x01(\tR\rcomponentType\x12B\n" +
	"\x05props\x18\x03 \x03(\v2,.lumina.v1.CreateComponentRequest.PropsEntryR\x05props\x1aJ\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.lumina.v1.ValueR\x05value:\x028\x01\"v\n" +
	"\x17CreateComponentResponse\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x128\n" +
	"\binstance\x18\x02 \x01(\v2\x1c.lumina.v1.ComponentInstanceR\binstance\"\xdb\x02\n" +
	"\x16UpdateComponentRequest\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12B\n" +
	"\x05props\x18\x02 \x03(\v2,.lumina.v1.UpdateComponentRequest.PropsEntryR\x05props\x12B\n" +
	"\x05state\x18\x03 \x03(\v2,.lumina.v1.UpdateComponentRequest.StateEntryR\x05state\x1aJ\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.lumina.v1.ValueR\x05value:\x028\x01\x1aJ\n" +
	"\n" +
	"StateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.lumina.v1.ValueR\x05value:\x028\x01\"m\n" +
	"\x17UpdateComponentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\binstance\x18\x02 \x01(\v2\x1c.lumina.v1.ComponentInstanceR\binstance\";\n" +
	"\x16DeleteComponentRequest\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\"3\n" +
	"\x17DeleteComponentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x15QueryComponentRequest\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\"R\n" +
	"\x16QueryComponentResponse\x128\n" +
	"\binstance\x18\x01 \x01(\v2\x1c.lumina.v1.ComponentInstanceR\binstance\";\n" +
	"\x14ComponentTreeRequest\x12#\n" +
	"\rinclude_state\x18\x01 \x01(\bR\fincludeState\"l\n" +
	"\x15ComponentTreeResponse\x122\n" +
	"\x05roots\x18\x01 \x03(\v2\x1c.lumina.v1.ComponentInstanceR\x05roots\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"<\n" +
	"\x17InspectComponentRequest\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\"\xf5\x01\n" +
	"\x18InspectComponentResponse\x128\n" +
	"\binstance\x18\x01 \x01(\v2\x1c.lumina.v1.ComponentInstanceR\binstance\x122\n" +
	"\n" +
	"hook_calls\x18\x02 \x03(\v2\x13.lumina.v1.HookCallR\thookCalls\x12\"\n" +
	"\rcreated_at_us\x18\x03 \x01(\x03R\vcreatedAtUs\x12$\n" +
	"\x0elast_render_us\x18\x04 \x01(\x03R\flastRenderUs\x12!\n" +
	"\frender_count\x18\x05 \x01(\x05R\vrenderCount\"\x85\x02\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fnumber_value\x18\x03 \x01(\x01H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x125\n" +
	"\n" +
	"list_value\x18\x05 \x01(\v2\x14.lumina.v1.ListValueH\x00R\tlistValue\x122\n" +
	"\tmap_value\x18\x06 \x01(\v2\x13.lumina.v1.MapValueH\x00R\bmapValueB\a\n" +
	"\x05value\"3\n" +
	"\tListValue\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.lumina.v1.ValueR\x05items\"\x94\x01\n" +
	"\bMapValue\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .lumina.v1.MapValue.EntriesEntryR\aentries\x1aL\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.lumina.v1.ValueR\x05value:\x028\x01\"D\n" +
	"\fBatchRequest\x124\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x14.lumina.v1.OperationR\n" +
	"operations\"\xdc\x01\n" +
	"\tOperation\x12%\n" +
	"\x0eoperation_type\x18\x01 \x01(\tR\roperationType\x12!\n" +
	"\fcomponent_id\x18\x02 \x01(\tR\vcomponentId\x128\n" +
	"\x06params\x18\x03 \x03(\v2 .lumina.v1.Operation.ParamsEntryR\x06params\x1aK\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.lumina.v1.ValueR\x05value:\x028\x01\"E\n" +
	"\rBatchResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.lumina.v1.OperationResultR\aresults\"U\n" +
	"\x0fOperationResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04dataB(Z&github.com/akzj/lumina/proto/v1;lumiv1b\x06proto3"

var (
	file_proto_v1_lumina_proto_rawDescOnce sync.Once
	file_proto_v1_lumina_proto_rawDescData []byte
)

func file_proto_v1_lumina_proto_rawDescGZIP() []byte {
	file_proto_v1_lumina_proto_rawDescOnce.Do(func() {
		file_proto_v1_lumina_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_lumina_proto_rawDesc), len(file_proto_v1_lumina_proto_rawDesc)))
	})
	return file_proto_v1_lumina_proto_rawDescData
}

var file_proto_v1_lumina_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_v1_lumina_proto_goTypes = []any{
	(*ComponentInstance)(nil),        // 0: lumina.v1.ComponentInstance
	(*ComponentFactory)(nil),         // 1: lumina.v1.ComponentFactory
	(*VNode)(nil),                    // 2: lumina.v1.VNode
	(*RenderResult)(nil),             // 3: lumina.v1.RenderResult
	(*HookCall)(nil),                 // 4: lumina.v1.HookCall
	(*StateUpdate)(nil),              // 5: lumina.v1.StateUpdate
	(*MouseEvent)(nil),               // 6: lumina.v1.MouseEvent
	(*KeyboardEvent)(nil),            // 7: lumina.v1.KeyboardEvent
	(*EventMessage)(nil),             // 8: lumina.v1.EventMessage
	(*CreateComponentRequest)(nil),   // 9: lumina.v1.CreateComponentRequest
	(*CreateComponentResponse)(nil),  // 10: lumina.v1.CreateComponentResponse
	(*UpdateComponentRequest)(nil),   // 11: lumina.v1.UpdateComponentRequest
	(*UpdateComponentResponse)(nil),  // 12: lumina.v1.UpdateComponentResponse
	(*DeleteComponentRequest)(nil),   // 13: lumina.v1.DeleteComponentRequest
	(*DeleteComponentResponse)(nil),  // 14: lumina.v1.DeleteComponentResponse
	(*QueryComponentRequest)(nil),    // 15: lumina.v1.QueryComponentRequest
	(*QueryComponentResponse)(nil),   // 16: lumina.v1.QueryComponentResponse
	(*ComponentTreeRequest)(nil),     // 17: lumina.v1.ComponentTreeRequest
	(*ComponentTreeResponse)(nil),    // 18: lumina.v1.ComponentTreeResponse
	(*InspectComponentRequest)(nil),  // 19: lumina.v1.InspectComponentRequest
	(*InspectComponentResponse)(nil), // 20: lumina.v1.InspectComponentResponse
	(*Value)(nil),                    // 21: lumina.v1.Value
	(*ListValue)(nil),                // 22: lumina.v1.ListValue
	(*MapValue)(nil),                 // 23: lumina.v1.MapValue
	(*BatchRequest)(nil),             // 24: lumina.v1.BatchRequest
	(*Operation)(nil),                // 25: lumina.v1.Operation
	(*BatchResponse)(nil),            // 26: lumina.v1.BatchResponse
	(*OperationResult)(nil),          // 27: lumina.v1.OperationResult
	nil,                              // 28: lumina.v1.ComponentInstance.PropsEntry
	nil,                              // 29: lumina.v1.ComponentInstance.StateEntry
	nil,                              // 30: lumina.v1.VNode.PropsEntry
	nil,                              // 31: lumina.v1.CreateComponentRequest.PropsEntry
	nil,                              // 32: lumina.v1.UpdateComponentRequest.PropsEntry
	nil,                              // 33: lumina.v1.UpdateComponentRequest.StateEntry
	nil,                              // 34: lumina.v1.MapValue.EntriesEntry
	nil,                              // 35: lumina.v1.Operation.ParamsEntry
}
var file_proto_v1_lumina_proto_depIdxs = []int32{
	28, // 0: lumina.v1.ComponentInstance.props:type_name -> lumina.v1.ComponentInstance.PropsEntry
	29, // 1: lumina.v1.ComponentInstance.state:type_name -> lumina.v1.ComponentInstance.StateEntry
	30, // 2: lumina.v1.VNode.props:type_name -> lumina.v1.VNode.PropsEntry
	2,  // 3: lumina.v1.VNode.children:type_name -> lumina.v1.VNode
	2,  // 4: lumina.v1.RenderResult.vdom:type_name -> lumina.v1.VNode
	21, // 5: lumina.v1.HookCall.args:type_name -> lumina.v1.Value
	21, // 6: lumina.v1.HookCall.result:type_name -> lumina.v1.Value
	21, // 7: lumina.v1.StateUpdate.old_value:type_name -> lumina.v1.Value
	21, // 8: lumina.v1.StateUpdate.new_value:type_name -> lumina.v1.Value
	6,  // 9: lumina.v1.EventMessage.mouse:type_name -> lumina.v1.MouseEvent
	7,  // 10: lumina.v1.EventMessage.keyboard:type_name -> lumina.v1.KeyboardEvent
	31, // 11: lumina.v1.CreateComponentRequest.props:type_name -> lumina.v1.CreateComponentRequest.PropsEntry
	0,  // 12: lumina.v1.CreateComponentResponse.instance:type_name -> lumina.v1.ComponentInstance
	32, // 13: lumina.v1.UpdateComponentRequest.props:type_name -> lumina.v1.UpdateComponentRequest.PropsEntry
	33, // 14: lumina.v1.UpdateComponentRequest.state:type_name -> lumina.v1.UpdateComponentRequest.StateEntry
	0,  // 15: lumina.v1.UpdateComponentResponse.instance:type_name -> lumina.v1.ComponentInstance
	0,  // 16: lumina.v1.QueryComponentResponse.instance:type_name -> lumina.v1.ComponentInstance
	0,  // 17: lumina.v1.ComponentTreeResponse.roots:type_name -> lumina.v1.ComponentInstance
	0,  // 18: lumina.v1.InspectComponentResponse.instance:type_name -> lumina.v1.ComponentInstance
	4,  // 19: lumina.v1.InspectComponentResponse.hook_calls:type_name -> lumina.v1.HookCall
	22, // 20: lumina.v1.Value.list_value:type_name -> lumina.v1.ListValue
	23, // 21: lumina.v1.Value.map_value:type_name -> lumina.v1.MapValue
	21, // 22: lumina.v1.ListValue.items:type_name -> lumina.v1.Value
	34, // 23: lumina.v1.MapValue.entries:type_name -> lumina.v1.MapValue.EntriesEntry
	25, // 24: lumina.v1.BatchRequest.operations:type_name -> lumina.v1.Operation
	35, // 25: lumina.v1.Operation.params:type_name -> lumina.v1.Operation.ParamsEntry
	27, // 26: lumina.v1.BatchResponse.results:type_name -> lumina.v1.OperationResult
	21, // 27: lumina.v1.ComponentInstance.PropsEntry.value:type_name -> lumina.v1.Value
	21, // 28: lumina.v1.ComponentInstance.StateEntry.value:type_name -> lumina.v1.Value
	21, // 29: lumina.v1.VNode.PropsEntry.value:type_name -> lumina.v1.Value
	21, // 30: lumina.v1.CreateComponentRequest.PropsEntry.value:type_name -> lumina.v1.Value
	21, // 31: lumina.v1.UpdateComponentRequest.PropsEntry.value:type_name -> lumina.v1.Value
	21, // 32: lumina.v1.UpdateComponentRequest.StateEntry.value:type_name -> lumina.v1.Value
	21, // 33: lumina.v1.MapValue.EntriesEntry.value:type_name -> lumina.v1.Value
	21, // 34: lumina.v1.Operation.ParamsEntry.value:type_name -> lumina.v1.Value
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_proto_v1_lumina_proto_init() }
func file_proto_v1_lumina_proto_init() {
	if File_proto_v1_lumina_proto != nil {
		return
	}
	file_proto_v1_lumina_proto_msgTypes[8].OneofWrappers = []any{
		(*EventMessage_Mouse)(nil),
		(*EventMessage_Keyboard)(nil),
	}
	file_proto_v1_lumina_proto_msgTypes[21].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_NumberValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_MapValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_lumina_proto_rawDesc), len(file_proto_v1_lumina_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_lumina_proto_goTypes,
		DependencyIndexes: file_proto_v1_lumina_proto_depIdxs,
		MessageInfos:      file_proto_v1_lumina_proto_msgTypes,
	}.Build()
	File_proto_v1_lumina_proto = out.File
	file_proto_v1_lumina_proto_goTypes = nil
	file_proto_v1_lumina_proto_depIdxs = nil
}
